---
title: "Lab 00 - Hello IDS!"
author: "Katarzyna Kuszner"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

### Exercises 16-17

We set up the data frame. Edit the data below to include information about your team members.

```{r setup-tibble}
team_data <- tibble(
  name = c("Asini", "Lily", "Iona", 
           "Tanvee", "Sofea", "Tyra"),
  github_username = c("asinisw397", "lilymck", "ionaconnelly", 
                      "username 3", "s-ofea", "tyratann"), 
  colour = c("pink", "green", "blue", 
             "blue", "white", "purple"),
  hobby = c("Playing the violin", "Music", "Swimming", 
            "Music", "Driving", "guitar"),
  favourite_number = c(9, 6, 10, 7, 9, 2)
  )

team_data
```

### Exercise 18

We now work on visualising our data. 

```{r bar-plot}
p1 <- ggplot(data = team_data, 
             mapping = aes(x = github_username, 
                           y = favourite_number,
                           fill = colour), 
             ) +
   geom_col() +
   scale_fill_identity()
p1
```

The plot shows team members favourite number on the y axis versus their github username on the x axis.

